import React from 'react';
import { ApiResponse } from '../types';

interface JsonViewerProps {
  data: ApiResponse | null;
}

const JsonViewer: React.FC<JsonViewerProps> = ({ data }) => {
  if (!data) return null;

  const jsonString = JSON.stringify(data, null, 2);

  return (
    <div className="relative w-full h-full bg-[#1e293b] rounded-lg overflow-hidden border border-gray-700 shadow-xl flex flex-col">
      <div className="bg-[#0f172a] px-4 py-2 border-b border-gray-700 flex justify-between items-center">
        <span className="text-xs font-mono text-gray-400">Response JSON</span>
        <div className="flex space-x-2">
          <div className="w-3 h-3 rounded-full bg-red-500/20 border border-red-500/50"></div>
          <div className="w-3 h-3 rounded-full bg-yellow-500/20 border border-yellow-500/50"></div>
          <div className="w-3 h-3 rounded-full bg-green-500/20 border border-green-500/50"></div>
        </div>
      </div>
      <div className="flex-1 overflow-auto custom-scrollbar p-4">
        <pre className="text-xs md:text-sm font-mono text-green-400 whitespace-pre">
          {jsonString}
        </pre>
      </div>
      <div className="bg-[#0f172a] px-4 py-2 border-t border-gray-700 text-[10px] text-gray-500 text-right">
        Generated by Gemini 2.5 Flash
      </div>
    </div>
  );
};

export default JsonViewer;
